[[opener.play]]
run = 'vlc "$@"'
orphan = true
for = "unix"

[[opener.play]]
run = '"C:\Program Files\vlc.exe" %*'
orphan = true
for = "windows"

[[opener.edit]]
run = '$EDITOR "$@"'
block = true
for = "unix"

[[opener.edit]]
run = "%EDITOR% %*"
block = true
for = "windows"

[[opener.open]]
run = 'xdg-open "$@"'
desc = "Open"
